package haraldr.event;

public enum EventType
{
    KEY_PRESSED, KEY_RELEASED, CHAR_TYPED,
    MOUSE_PRESSED, MOUSE_RELEASED, MOUSE_SCROLLED, MOUSE_MOVED, MOUSE_DRAGGED,
    WINDOW_RESIZED, WINDOW_CLOSED, WINDOW_FOCUS,
    FRAME_INFO_UPDATED,

    PARENT_COLLAPSED
}
