package haraldr.event;

public enum EventType
{
    KEY_PRESSED, KEY_RELEASED, CHAR_TYPED,
    MOUSE_PRESSED, MOUSE_RELEASED, MOUSE_SCROLLED, MOUSE_MOVED,
    WINDOW_RESIZED, WINDOW_CLOSED, WINDOW_FOCUS,
    GUI_TOGGLED,
    DEBUG_SCREEN_UPDATED
}
