package com.game.event;

public enum EventType {

    KEY_PRESSED, KEY_RELEASED, KEY_TYPED,
    MOUSE_PRESSED, MOUSE_RELEASED, MOUSE_SCROLLED, MOUSE_MOVED,
    WINDOW_RESIZED, WINDOW_CLOSED,
    GUI_TOGGLED,
    DEBUG_SCREEN_UPDATED
}
